package models

// LoanProductData struct for LoanProductData
type LoanProductData struct {
	Id                                          int64                                   `json:"id,omitempty"`
	Name                                        string                                  `json:"name,omitempty"`
	Description                                 string                                  `json:"description,omitempty"`
	FundId                                      int64                                   `json:"fundId,omitempty"`
	FundName                                    string                                  `json:"fundName,omitempty"`
	StartDate                                   string                                  `json:"startDate,omitempty"`
	CloseDate                                   string                                  `json:"closeDate,omitempty"`
	Currency                                    CurrencyData                            `json:"currency,omitempty"`
	Principal                                   float32                                 `json:"principal,omitempty"`
	MinPrincipal                                float32                                 `json:"minPrincipal,omitempty"`
	MaxPrincipal                                float32                                 `json:"maxPrincipal,omitempty"`
	NumberOfRepayments                          int32                                   `json:"numberOfRepayments,omitempty"`
	MinNumberOfRepayments                       int32                                   `json:"minNumberOfRepayments,omitempty"`
	MaxNumberOfRepayments                       int32                                   `json:"maxNumberOfRepayments,omitempty"`
	RepaymentEvery                              int32                                   `json:"repaymentEvery,omitempty"`
	RepaymentFrequencyType                      EnumOptionData                          `json:"repaymentFrequencyType,omitempty"`
	InterestRatePerPeriod                       float32                                 `json:"interestRatePerPeriod,omitempty"`
	MinInterestRatePerPeriod                    float32                                 `json:"minInterestRatePerPeriod,omitempty"`
	MaxInterestRatePerPeriod                    float32                                 `json:"maxInterestRatePerPeriod,omitempty"`
	InterestRateFrequencyType                   EnumOptionData                          `json:"interestRateFrequencyType,omitempty"`
	AnnualInterestRate                          float32                                 `json:"annualInterestRate,omitempty"`
	InterestRateDifferential                    float32                                 `json:"interestRateDifferential,omitempty"`
	MinDifferentialLendingRate                  float32                                 `json:"minDifferentialLendingRate,omitempty"`
	DefaultDifferentialLendingRate              float32                                 `json:"defaultDifferentialLendingRate,omitempty"`
	MaxDifferentialLendingRate                  float32                                 `json:"maxDifferentialLendingRate,omitempty"`
	AmortizationType                            EnumOptionData                          `json:"amortizationType,omitempty"`
	InterestType                                EnumOptionData                          `json:"interestType,omitempty"`
	InterestCalculationPeriodType               EnumOptionData                          `json:"interestCalculationPeriodType,omitempty"`
	AllowPartialPeriodInterestCalcualtion       bool                                    `json:"allowPartialPeriodInterestCalcualtion,omitempty"`
	InArrearsTolerance                          float32                                 `json:"inArrearsTolerance,omitempty"`
	TransactionProcessingStrategyId             int64                                   `json:"transactionProcessingStrategyId,omitempty"`
	TransactionProcessingStrategyName           string                                  `json:"transactionProcessingStrategyName,omitempty"`
	GraceOnPrincipalPayment                     int32                                   `json:"graceOnPrincipalPayment,omitempty"`
	RecurringMoratoriumOnPrincipalPeriods       int32                                   `json:"recurringMoratoriumOnPrincipalPeriods,omitempty"`
	GraceOnInterestPayment                      int32                                   `json:"graceOnInterestPayment,omitempty"`
	GraceOnInterestCharged                      int32                                   `json:"graceOnInterestCharged,omitempty"`
	GraceOnArrearsAgeing                        int32                                   `json:"graceOnArrearsAgeing,omitempty"`
	DaysInMonthType                             EnumOptionData                          `json:"daysInMonthType,omitempty"`
	DaysInYearType                              EnumOptionData                          `json:"daysInYearType,omitempty"`
	InterestRecalculationData                   LoanProductInterestRecalculationData    `json:"interestRecalculationData,omitempty"`
	PrincipalVariationsForBorrowerCycle         []LoanProductBorrowerCycleVariationData `json:"principalVariationsForBorrowerCycle,omitempty"`
	InterestRateVariationsForBorrowerCycle      []LoanProductBorrowerCycleVariationData `json:"interestRateVariationsForBorrowerCycle,omitempty"`
	NumberOfRepaymentVariationsForBorrowerCycle []LoanProductBorrowerCycleVariationData `json:"numberOfRepaymentVariationsForBorrowerCycle,omitempty"`
	FundOptions                                 []FundData                              `json:"fundOptions,omitempty"`
	RepaymentFrequencyTypeOptions               []EnumOptionData                        `json:"repaymentFrequencyTypeOptions,omitempty"`
	InterestRateFrequencyTypeOptions            []EnumOptionData                        `json:"interestRateFrequencyTypeOptions,omitempty"`
	AmortizationTypeOptions                     []EnumOptionData                        `json:"amortizationTypeOptions,omitempty"`
	InterestTypeOptions                         []EnumOptionData                        `json:"interestTypeOptions,omitempty"`
	InterestCalculationPeriodTypeOptions        []EnumOptionData                        `json:"interestCalculationPeriodTypeOptions,omitempty"`
	ChargeOptions                               []ChargeData                            `json:"chargeOptions,omitempty"`
	MultiDisburseLoan                           bool                                    `json:"multiDisburseLoan,omitempty"`
	OutstandingLoanBalance                      float32                                 `json:"outstandingLoanBalance,omitempty"`
	GetloanProductConfigurableAttributes        LoanProductConfigurableAttributes       `json:"getloanProductConfigurableAttributes,omitempty"`
	MinimumGapBetweenInstallments               int32                                   `json:"minimumGapBetweenInstallments,omitempty"`
	MaximumGapBetweenInstallments               int32                                   `json:"maximumGapBetweenInstallments,omitempty"`
	EqualAmortization                           bool                                    `json:"equalAmortization,omitempty"`
	LinkedToFloatingInterestRates               bool                                    `json:"linkedToFloatingInterestRates,omitempty"`
	VariableInstallmentsAllowed                 bool                                    `json:"variableInstallmentsAllowed,omitempty"`
	InterestRecalculationEnabled                bool                                    `json:"interestRecalculationEnabled,omitempty"`
	FloatingInterestRateCalculationAllowed      bool                                    `json:"floatingInterestRateCalculationAllowed,omitempty"`
	CompoundingToBePostedAsTransaction          bool                                    `json:"compoundingToBePostedAsTransaction,omitempty"`
}
