package models

// PutStandingInstructionsStandingInstructionIdRequest PutStandingInstructionsStandingInstructionIdRequest
type PutStandingInstructionsStandingInstructionIdRequest struct {
	RecurrenceInterval int32 `json:"recurrenceInterval,omitempty"`
}
